### ISSUE TITLE
Mozilla Support?

### ISSUE THREAD

**Issue by yofret** [AlexSugak/react-svg-pathline#3]
Hi! This is a great component to draw curved pathline, but I'm having problems with FireFox, for some reason the path won't work.

```javascript
  
	renderPath() {
			return <PathLine
						points={ [{0,72}, {10, 72}, {40,111}, {60,111}] } 
						stroke="#CF0072" 
						strokeWidth="5"
						fill="none"
						r={18}
					/>
	}
```
the path will be rendered in the DOM, but no line will appear, this just happens for Firefox, any Ideas?

Thanks for this awesome component

**Comment by AlexSugak** [comment]
Looks like Mozilla does not like commas in svg path property.
Please try with latest version
