### ISSUE TITLE
Dependency on React v15

### ISSUE THREAD

**Issue by aranwe** [AlexSugak/react-svg-pathline#4]
This package depends on React v15, although v16 has been around for quite a while.
This package appears to work fine with v16, only peerDependencies need to be updated in package.json.

Should I submit a PR or can you fix it? :)
Thank you!

**Comment by AlexSugak** [comment]
Hi!

Will defiantly update to v16. Not sure when I have time though.
If you want it quick, I will of course welcome a PR.

Thanks.

**Comment by AlexSugak** [comment]
Thanks for PR!
Could you please try the 0.5.0 version with v16 react dependency?
