### ISSUE TITLE
Does it work with coordinates

### ISSUE THREAD

**Issue by jaimeknd77** [AlexSugak/react-svg-pathline#6]
I am working on a university project and I would like to add to a map, given some coordinates, lines that connect these coordinates.

`<svg>
<PathLine
points={[{x: 43.354831, y: -5.851303}, {x: 43.356440, y: -5.854693}]}
stroke="red"
strokeWidth="3"
fill="none"
r={10}
/>
</svg>`

I don't know if it works with coordinates or I have to do it differently

**Comment by AlexSugak** [comment]
Hi,

The original application of this library was for drawing "paths" on a leaflet-based geomap. So yes, it should work.

You may need to "map" geo-coordinates to zero-based x-y coordinates of an svg shape layered on top of the map though.
